export { default as avatar } from './avatar-pro.png';
export { default as logo_eplus } from './logo_eplus.png';
export { default as logo } from './logo.png';
export { default as background } from './background.png';
export { default as box } from './box.png';
export { default as PR_Monochromatic } from './PR_Monochromatic.png';
export { default as category } from './category.png';
export { default as tag } from './tag.png';
export { default as historyBanner } from './history-banner.png';
export { default as achievementBanner } from './achievement-banner.png';
export { default as achievementEco } from './achievement-eco.png';
export { default as visionBannerEco } from './vision-banner-eco.png';
export { default as togetherEco } from './together-eco.png';
export { default as eplusMarket } from './eplus-market.png';
export { default as eplusBanner2 } from './banner-eplus-2.png';
export { default as vmvEplus } from './vision-mission-value-eplus.png';
export { default as bannerAboutEcoMobi } from './banner-veeco-mobi.jpg';
export { default as roundedLogoEplus } from './logo-eplus.png';
export { default as roundedLogoEco } from './logo-eco.png';
export { default as roundedLogoVNVC } from './logo-vnvc.png';
export { default as roundedLogoTamAnh } from './logo-tamanh.png';
export { default as pgrThanhLap1 } from './pgr-thanhlap1.png';
export { default as pgrThanhLap2 } from './pgr-thanhlap2.png';
export { default as pgrThanhLap1Left } from './pgr-thanhlap-left1.png';
export { default as pgrThanhLap2Left } from './pgr-thanhlap-left2.png';
export { default as vnvcAds } from './cnvc_ads_banner.png';
export { default as jexAds } from './jex_ads_banner.png';
export { default as bgEplus } from './bg_eplus.png';
export { default as ecoPharmaLogo } from './eco-favicon.png';
export { default as tamAnhHosLogo } from './TA LOGO.png';
export { default as tamriLogo } from './Logo-TAMRI.png';
export { default as vnvcLogo } from './VNVC.png';
export { default as vmvBackground } from './vmv_background.png';
export { default as bottomBannerEco } from './bottom_banner_eco.png';
export { default as bottomBannerEcoMobile } from './bottom_banner_eco_mobile.png';
export { default as centerBgBannerEplus } from './bg_center_about_eplus.png';
export { default as logoHST } from './icon_hesinhthai.png';
export { default as imageQuyTrinh } from './icon_quy_trinh.png';
export { default as imageJscGroup } from './home_logo_group.png';
export { default as imageJscGroup2 } from './imageHstGroup.png';
export { default as BlueBg1920500 } from './BlueBg (1920x500).png';
export { default as GrayBg1920500 } from './GrayBg (1920x500).png';
export { default as introHistoryBgrMobile } from './intro-history-mobile-bgr-removebg-preview.png';
export { default as introHistoryBgrMobile2 } from './intro-history-mobile-bgr2_prev_ui.png';
export { default as introHistoryBgrMobile3 } from './intro-history-mobile-bgr3_prev_ui.png';
// export { default as tuyenDVKH } from './tuyen_dvkh.png';
// export { default as tuyenContentSEO } from './tuyen_contenseo.png';
// export { default as tuyenSocialContent } from './tuyen_socialcontent.png';
// export { default as tuyentdv } from './tuyen_tdv.png';
